//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireplace.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusyRoomTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusyRoomTable()
        {
            this.RoomsHotelTable = new HashSet<RoomsHotelTable>();
        }
    
        public int PersonalNumber_Busy { get; set; }
        public string Title_Busy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomsHotelTable> RoomsHotelTable { get; set; }
    }
}
