//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireplace.AppDataFolder.ModelFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FireplaceEntities : DbContext
    {
        public FireplaceEntities()
            : base("name=FireplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageTable> ImageTable { get; set; }
        public virtual DbSet<PasspordDataUserTable> PasspordDataUserTable { get; set; }
        public virtual DbSet<PaulTable> PaulTable { get; set; }
        public virtual DbSet<RoleUserTable> RoleUserTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
