//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireplace.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelTable()
        {
            this.RoomsHotelTable = new HashSet<RoomsHotelTable>();
        }
    
        public int PersonalNumber_Hotel { get; set; }
        public string Name_Hotel { get; set; }
        public string pnUserAdd_Hotel { get; set; }
        public int pnCityLocal_Hotel { get; set; }
        public string StreetLocal_Hotel { get; set; }
        public int HomeLocal_Hotel { get; set; }
        public int NumberFloors_Hotel { get; set; }
    
        public virtual CityTable CityTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomsHotelTable> RoomsHotelTable { get; set; }
    }
}
