//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fireplace.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasspordDataUserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PasspordDataUserTable()
        {
            this.UserTable = new HashSet<UserTable>();
        }
    
        public string PassportSeries_PasspordDataUser { get; set; }
        public string PassportNumber_PasspordDataUser { get; set; }
        public string Surname_PasspordDataUser { get; set; }
        public string Name_PasspordDataUser { get; set; }
        public string Middlename_PasspordDataUser { get; set; }
        public string PassportHasBeenIssued_PasspordDataUser { get; set; }
        public System.DateTime DateIssue_PasspordDataUser { get; set; }
        public string UnitCode_PasspordDataUser { get; set; }
        public int pnPaul_PasspordDataUser { get; set; }
        public System.DateTime DateBirth_PasspordDataUser { get; set; }
        public string PlaceBirth_PasspordDataUser { get; set; }
    
        public virtual PaulTable PaulTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTable { get; set; }
    }
}
